data_load:
  train_dataset: data/raw/processed_(A+B)_data.xlsx
  test_dataset: data/raw/processed_C_data.xlsx

data_split:
  trainset_path: data/train_(A+B).csv
  testset_path: data/test_C.csv
